from __future__ import annotations

from fastapi.testclient import TestClient

from src.agent.artifacts import generate_artifact
from src.frontend.webapp.server import app as app_mod
from src.frontend.webapp.server import deps


def test_download_generated_artifact_and_slidev_source(tmp_path, monkeypatch):
    async def _noop():
        pass

    monkeypatch.setattr(deps, "startup", _noop)
    monkeypatch.setattr(deps, "shutdown", _noop)
    monkeypatch.setenv("ARTIFACTS_DIR", str(tmp_path))
    artifact = generate_artifact(
        format="pptx",
        title="Agent Deck",
        content="# Intro\n\n- Generated by Agent",
    )

    with TestClient(app_mod.app) as client:
        presentation = client.get(artifact.download_url)
        slidev = client.get(artifact.slidev_url)

    assert presentation.status_code == 200
    assert presentation.headers["content-type"].startswith(
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    )
    assert "attachment" in presentation.headers["content-disposition"]
    assert slidev.status_code == 200
    assert "theme: default" in slidev.text


def test_download_missing_artifact_returns_404(monkeypatch, tmp_path):
    async def _noop():
        pass

    monkeypatch.setattr(deps, "startup", _noop)
    monkeypatch.setattr(deps, "shutdown", _noop)
    monkeypatch.setenv("ARTIFACTS_DIR", str(tmp_path))
    with TestClient(app_mod.app) as client:
        response = client.get(
            "/api/artifacts/00000000-0000-0000-0000-000000000000/download"
        )

    assert response.status_code == 404
    assert response.json()["detail"] == "生成的文件不存在或已被清理"
