from __future__ import annotations

from fastapi.testclient import TestClient

from src.agent.artifacts import generate_artifact
from src.frontend.webapp.server import app as app_mod
from src.frontend.webapp.server import deps


def test_scoped_download_and_pi_proxy(tmp_path, monkeypatch):
    from hashlib import sha256
    from config.schema import AppConfig
    from src.engine.scope import MemoryScope
    from src.engine.trusted_scope import ScopeBinding
    from src.agent import artifacts

    async def noop():
        pass

    monkeypatch.setattr(deps, "startup", noop)
    monkeypatch.setattr(deps, "shutdown", noop)
    monkeypatch.setenv("ARTIFACTS_DIR", str(tmp_path))
    monkeypatch.setattr(
        artifacts, "_generate_docx", lambda path, *_: path.write_bytes(b"private")
    )
    monkeypatch.setattr(
        deps,
        "_app_config",
        AppConfig.model_validate(
            {"engine": {"memory": {"enabled": True, "features": {"scope": True}}}}
        ),
    )
    monkeypatch.setattr(
        deps.settings,
        "memory_scope_bindings",
        {sha256(b"a").hexdigest(): ScopeBinding(bank_id="A")},
    )
    artifact = generate_artifact(
        format="docx",
        title="private",
        content="private",
        scope=MemoryScope(bank_id="A"),
    )
    with TestClient(app_mod.app) as client:
        assert client.get(artifact.download_url).status_code == 404
        assert (
            client.get(
                artifact.download_url, headers={"x-tkb-scope-token": "a"}
            ).content
            == b"private"
        )
        import httpx
        from src.frontend.webapp.server import routes_agent

        def upstream(request):
            assert request.headers["x-tkb-scope-token"] == "a"
            return httpx.Response(201, json={"id": "owned"})

        monkeypatch.setattr(
            routes_agent,
            "_pi_client",
            lambda *args: httpx.AsyncClient(transport=httpx.MockTransport(upstream)),
        )
        assert (
            client.post(
                "/api/agent/sessions", headers={"x-tkb-scope-token": "a"}
            ).status_code
            == 201
        )
        assert (
            client.post(
                "/api/agent/sessions", headers={"x-tkb-scope-token": "forged"}
            ).status_code
            == 403
        )


def test_download_generated_artifact_and_slidev_source(tmp_path, monkeypatch):
    async def _noop():
        pass

    monkeypatch.setattr(deps, "startup", _noop)
    monkeypatch.setattr(deps, "shutdown", _noop)
    monkeypatch.setenv("ARTIFACTS_DIR", str(tmp_path))
    artifact = generate_artifact(
        format="pptx",
        title="Agent Deck",
        content="# Intro\n\n- Generated by Agent",
    )

    with TestClient(app_mod.app) as client:
        presentation = client.get(artifact.download_url)
        slidev = client.get(artifact.slidev_url)

    assert presentation.status_code == 200
    assert presentation.headers["content-type"].startswith(
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    )
    assert "attachment" in presentation.headers["content-disposition"]
    assert slidev.status_code == 200
    assert "theme: default" in slidev.text


def test_download_missing_artifact_returns_404(monkeypatch, tmp_path):
    async def _noop():
        pass

    monkeypatch.setattr(deps, "startup", _noop)
    monkeypatch.setattr(deps, "shutdown", _noop)
    monkeypatch.setenv("ARTIFACTS_DIR", str(tmp_path))
    with TestClient(app_mod.app) as client:
        response = client.get(
            "/api/artifacts/00000000-0000-0000-0000-000000000000/download"
        )

    assert response.status_code == 404
    assert response.json()["detail"] == "生成的文件不存在或已被清理"
