#!/usr/bin/env bash
# Bring up the WeKnora stack (host-side: needs podman or docker + compose).
#
# WeKnora runs as a compose stack — app (:8080), frontend (:80), docreader
# (PDF/image/Excel parser), ParadeDB pgvector postgres (DB + vectors), redis.
# Its source is vendored in this repo as a git submodule at vendors/WeKnora
# (pinned; init with `git submodule update --init --recursive vendors/WeKnora`).
# This script does NOT clone anything — it just brings the stack up. Bench
# config (.env) is generated under weknora-files/env/ and symlinked into the
# submodule as ./.env so compose's required `./.env` resolves to it.
#
# Idempotent: re-running pulls the latest images and brings up any missing
# services without rotating secrets (so existing encrypted data survives).
#
# Usage:
#   bash scripts/weknora/install-stack.sh
#   WEKNORA_SRC=/elsewhere bash scripts/weknora/install-stack.sh   # override

set -euo pipefail
source "$(dirname "$0")/_preflight.sh"

files_dir="$(get_weknora_files_dir)"
src_dir="$(get_weknora_src)"
env_dir="$files_dir/env"
env_file="$env_dir/.env"
mkdir -p "$env_dir"

# --- preflight ---------------------------------------------------------------

if ! test_compose_present; then
  write_step_fail "No compose implementation found. Install 'podman compose' (or 'docker compose')."
  echo "  WeKnora ships a docker-compose.yml that podman compose / docker compose both drive." >&2
  exit 2
fi
compose_cmd="$(detect_compose_cmd)"
write_step_ok "compose: $compose_cmd"

# The WeKnora source must be checked out (vendored submodule).
if [[ ! -f "$src_dir/docker-compose.yml" ]]; then
  write_step_fail "WeKnora source missing at $src_dir/docker-compose.yml."
  echo "  Initialize the submodule first:  git submodule update --init --recursive vendors/WeKnora" >&2
  exit 3
fi
if [[ ! -f "$src_dir/config/config.yaml" ]]; then
  write_step_fail "$src_dir/config/config.yaml missing — submodule checkout incomplete? Re-run: git submodule update --init --recursive vendors/WeKnora" >&2
  exit 3
fi
# skills/preloaded is bind-mounted too; ensure the dir exists (may be empty).
mkdir -p "$src_dir/skills/preloaded"
write_step_ok "WeKnora source present at $src_dir ($(cd "$src_dir" && git describe --tags --always 2>/dev/null || echo 'unknown rev'))"

if test_ollama_reachable; then
  write_step_ok "Ollama reachable at $(get_ollama_url) — embeddings + LLM via nomic-embed-text / qwen3.5."
else
  write_step_warn "Ollama NOT reachable at $(get_ollama_url). The stack will come up but ingest will fail to embed. Set WEKNORA_OLLAMA_URL if it moved."
fi

# --- 1. generate bench .env (only if absent — never rotate secrets) ----------

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

if [[ ! -f "$env_file" ]]; then
  write_step "generating $env_file"
  cat > "$env_file" <<EOF
# Generated by scripts/weknora/install-stack.sh on $(date -u +%FT%TZ).
# WeKnora bench config for the "Wren Adachi" corpus. DO NOT COMMIT (gitignored).
# The active copy is symlinked into the WeKnora submodule as ./.env for compose.

WEKNORA_VERSION=latest
GIN_MODE=release
TZ=UTC
# Corpus is English; this is the {{language}} prompt fallback.
WEKNORA_LANGUAGE=en-US
DISABLE_REGISTRATION=false

# Remote Ollama: nomic-embed-text (embeddings) + qwen3.5 (chat/summary/VLM).
OLLAMA_BASE_URL=$(get_ollama_url)

DB_DRIVER=postgres
RETRIEVE_DRIVER=postgres
STORAGE_TYPE=local
LOCAL_STORAGE_BASE_DIR=/data/files
STREAM_MANAGER_TYPE=redis

APP_HOST=app
APP_PORT=8080
FRONTEND_PORT=80
DOCREADER_PORT=50051

DB_USER=postgres
DB_PASSWORD=$(gen_secret)
DB_NAME=WeKnora

REDIS_PASSWORD=$(gen_secret)
REDIS_DB=0
REDIS_PREFIX=stream:

JWT_SECRET=$(gen_secret)
TENANT_AES_KEY=$(gen_secret)
SYSTEM_AES_KEY=$(gen_secret)
CRYPTO_MASTER_KEY=
CRYPTO_SALT=

AUTO_RECOVER_DIRTY=true
ENABLE_GRAPH_RAG=false
# Agent Skills sandbox not needed for this bench; disable to skip the image.
WEKNORA_SANDBOX_MODE=disabled
CONCURRENCY_POOL_SIZE=5
EOF
  chmod 600 "$env_file"
  write_step_ok ".env generated (secrets randomized)"
else
  write_step_ok "$env_file exists — reusing (secrets preserved)"
  # Re-affirm the Ollama URL in case it moved.
  if ! grep -q "^OLLAMA_BASE_URL=$(get_ollama_url)\$" "$env_file"; then
    sed -i -E "s|^OLLAMA_BASE_URL=.*|OLLAMA_BASE_URL=$(get_ollama_url)|" "$env_file"
    write_step_warn "updated OLLAMA_BASE_URL in $env_file"
  fi
fi

# Record the base URL the bench should talk to (compose publishes APP_PORT).
base_url="${WEKNORA_BASE_URL:-http://localhost:${APP_PORT_OVERRIDE:-8080}}"
echo "$base_url" > "$env_dir/url"

# Symlink the submodule's required ./.env to our bench-owned copy. WeKnora's own
# .gitignore covers .env, so this symlink keeps the submodule clean.
env_abs="$(readlink -f "$env_file")"
ln -sfn "$env_abs" "$src_dir/.env"
write_step_ok "linked $src_dir/.env -> $env_abs"

# --- 2. compose up -----------------------------------------------------------

write_step "$compose_cmd up -d (core services)"
( cd "$src_dir" && $compose_cmd up -d )
write_step_ok "compose up done"

# --- 3. wait for app healthy -------------------------------------------------

base_url="$(get_weknora_base_url)"
write_step "waiting for app healthy at $base_url ..."
deadline=$(( $(date +%s) + 180 ))
while ! curl -fsS --max-time 5 "$base_url/health" >/dev/null 2>&1; do
  if [[ $(date +%s) -ge $deadline ]]; then
    write_step_fail "app not healthy after 180s. Check: (cd $src_dir && $compose_cmd logs app docreader postgres)"
    exit 4
  fi
  sleep 5
done
write_step_ok "WeKnora app healthy at $base_url"

cat <<EOF

WeKnora stack is up. Next:
  bash scripts/weknora/bootstrap.sh     # mint tenant + API key, create KB
  bash scripts/weknora/ingest.sh        # ingest raw/
  # or all-in-one:
  bash scripts/weknora/run-all.sh --skip-stack

Web UI: $base_url  (landed page; registration open while DISABLE_REGISTRATION=false)
API:    $base_url/api/v1   Swagger at $base_url/swagger
EOF
