"""Download routes for documents generated by the Agent."""

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from src.agent.artifacts import resolve_artifact

router = APIRouter(prefix="/artifacts", tags=["artifacts"])


def _download(artifact_id: str, *, slidev: bool) -> FileResponse:
    try:
        path, artifact = resolve_artifact(artifact_id, slidev=slidev)
    except FileNotFoundError as exc:
        raise HTTPException(404, "生成的文件不存在或已被清理") from exc
    media_type = (
        "text/markdown; charset=utf-8"
        if slidev
        else {
            "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "pdf": "application/pdf",
            "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        }[artifact.format]
    )
    filename = artifact.slidev_filename if slidev else artifact.filename
    return FileResponse(path, media_type=media_type, filename=filename)


@router.get("/{artifact_id}/download")
async def download_artifact(artifact_id: str):
    return _download(artifact_id, slidev=False)


@router.get("/{artifact_id}/slidev")
async def download_slidev_source(artifact_id: str):
    return _download(artifact_id, slidev=True)
