"""Download routes for documents generated by the Agent."""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from src.agent.artifacts import resolve_artifact
from src.frontend.webapp.server import deps

router = APIRouter(prefix="/artifacts", tags=["artifacts"])


def _download(
    artifact_id: str, *, slidev: bool, request: Request | None = None
) -> FileResponse:
    try:
        path, artifact = resolve_artifact(
            artifact_id, slidev=slidev, scope=deps._binding(request).scope()
        )
    except FileNotFoundError as exc:
        raise HTTPException(404, "生成的文件不存在或已被清理") from exc
    media_type = (
        "text/markdown; charset=utf-8"
        if slidev
        else {
            "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "pdf": "application/pdf",
            "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        }[artifact.format]
    )
    filename = artifact.slidev_filename if slidev else artifact.filename
    return FileResponse(path, media_type=media_type, filename=filename)


@router.get("/{artifact_id}/download")
async def download_artifact(artifact_id: str, request: Request):
    return _download(artifact_id, slidev=False, request=request)


@router.get("/{artifact_id}/slidev")
async def download_slidev_source(artifact_id: str, request: Request):
    return _download(artifact_id, slidev=True, request=request)
